"""
Wavefront OBJ + MTL writer.

Writes a single .obj file with material groups and a companion .mtl file
annotated with pb_* extensions for the photon-beam renderer.
"""

from __future__ import annotations
import os
from typing import TextIO

import numpy as np

from .material_mapper import MtlMaterial


# ---------------------------------------------------------------------------
# OBJ Writer
# ---------------------------------------------------------------------------

class ObjWriter:
    """Aggregates mesh groups and writes a single OBJ file."""

    def __init__(self):
        self.groups: list[ObjGroup] = []

    def add_group(self, name: str, material: str,
                  positions: np.ndarray,
                  normals: np.ndarray | None,
                  uvs: np.ndarray | None,
                  faces: np.ndarray):
        """Add a mesh group.

        Parameters
        ----------
        positions : (N, 3) float32
        normals   : (N, 3) float32 or None
        uvs       : (N, 2) float32 or None
        faces     : (M, 3) int32, 0-based indices into vertices
        """
        self.groups.append(ObjGroup(name, material, positions, normals, uvs, faces))

    def write(self, obj_path: str, mtl_filename: str):
        """Write the OBJ file with global vertex indexing (numpy-vectorised)."""
        import io

        v_offset = 0
        vn_offset = 0
        vt_offset = 0

        with open(obj_path, 'wb') as f:
            f.write(f"# Generated by pbrt_to_obj converter\nmtllib {mtl_filename}\n\n".encode())

            for grp in self.groups:
                f.write(f"g {grp.name}\nusemtl {grp.material}\n".encode())

                # --- Vertices via np.savetxt (C-speed loop) ---
                buf = io.BytesIO()
                np.savetxt(buf, grp.positions.astype(np.float64),
                           fmt='v %.6f %.6f %.6f')
                f.write(buf.getvalue())

                # --- Texture coordinates ---
                if grp.uvs is not None:
                    buf = io.BytesIO()
                    np.savetxt(buf, grp.uvs.astype(np.float64),
                               fmt='vt %.6f %.6f')
                    f.write(buf.getvalue())

                # --- Normals ---
                if grp.normals is not None:
                    buf = io.BytesIO()
                    np.savetxt(buf, grp.normals.astype(np.float64),
                               fmt='vn %.6f %.6f %.6f')
                    f.write(buf.getvalue())

                # --- Faces (vectorised: build int array, format with savetxt) ---
                faces = grp.faces.astype(np.int64)
                has_uv = grp.uvs is not None
                has_n = grp.normals is not None

                if has_uv and has_n:
                    # Build (M, 9) array: v0 vt0 vn0  v1 vt1 vn1  v2 vt2 vn2
                    v = faces + v_offset + 1
                    t = faces + vt_offset + 1
                    n = faces + vn_offset + 1
                    arr = np.column_stack([v[:,0],t[:,0],n[:,0],
                                           v[:,1],t[:,1],n[:,1],
                                           v[:,2],t[:,2],n[:,2]])
                    buf = io.BytesIO()
                    np.savetxt(buf, arr, fmt='f %d/%d/%d %d/%d/%d %d/%d/%d')
                    f.write(buf.getvalue())
                elif has_n:
                    v = faces + v_offset + 1
                    n = faces + vn_offset + 1
                    arr = np.column_stack([v[:,0],n[:,0],
                                           v[:,1],n[:,1],
                                           v[:,2],n[:,2]])
                    buf = io.BytesIO()
                    np.savetxt(buf, arr, fmt='f %d//%d %d//%d %d//%d')
                    f.write(buf.getvalue())
                elif has_uv:
                    v = faces + v_offset + 1
                    t = faces + vt_offset + 1
                    arr = np.column_stack([v[:,0],t[:,0],
                                           v[:,1],t[:,1],
                                           v[:,2],t[:,2]])
                    buf = io.BytesIO()
                    np.savetxt(buf, arr, fmt='f %d/%d %d/%d %d/%d')
                    f.write(buf.getvalue())
                else:
                    v = faces + v_offset + 1
                    buf = io.BytesIO()
                    np.savetxt(buf, v, fmt='f %d %d %d')
                    f.write(buf.getvalue())

                v_offset += grp.positions.shape[0]
                if grp.uvs is not None:
                    vt_offset += grp.uvs.shape[0]
                if grp.normals is not None:
                    vn_offset += grp.normals.shape[0]

                f.write(b"\n")

        total_verts = sum(g.positions.shape[0] for g in self.groups)
        total_faces = sum(g.faces.shape[0] for g in self.groups)
        print(f"  OBJ: {len(self.groups)} groups, {total_verts:,} vertices, {total_faces:,} faces → {obj_path}")


class ObjGroup:
    __slots__ = ('name', 'material', 'positions', 'normals', 'uvs', 'faces')

    def __init__(self, name, material, positions, normals, uvs, faces):
        self.name = name
        self.material = material
        self.positions = positions
        self.normals = normals
        self.uvs = uvs
        self.faces = faces


# ---------------------------------------------------------------------------
# MTL Writer
# ---------------------------------------------------------------------------

def write_mtl(mtl_path: str, materials: dict[str, MtlMaterial]):
    """Write a Wavefront MTL file with pb_* extensions."""
    with open(mtl_path, 'w', encoding='utf-8') as f:
        f.write("# Generated by pbrt_to_obj converter\n")
        f.write("# pb_* extensions for photon-beam renderer\n\n")

        for name, mat in materials.items():
            f.write(f"newmtl {name}\n")

            # Comments (after newmtl for proper MTL parsing)
            for c in mat.comments:
                f.write(f"{c}\n")

            # Classic MTL
            f.write(f"Ka 0.000000 0.000000 0.000000\n")
            f.write(f"Kd {mat.Kd[0]:.6f} {mat.Kd[1]:.6f} {mat.Kd[2]:.6f}\n")
            if any(v > 0 for v in mat.Ks):
                f.write(f"Ks {mat.Ks[0]:.6f} {mat.Ks[1]:.6f} {mat.Ks[2]:.6f}\n")
            if any(v > 0 for v in mat.Ke):
                f.write(f"Ke {mat.Ke[0]:.6f} {mat.Ke[1]:.6f} {mat.Ke[2]:.6f}\n")
            f.write(f"Ns {mat.Ns:.2f}\n")
            f.write(f"Ni {mat.Ni:.4f}\n")
            f.write(f"d {mat.d:.4f}\n")
            f.write(f"illum {mat.illum}\n")

            # Transmission filter (for glass/dielectric materials)
            if mat.pb_brdf == 'dielectric' or mat.pb_transmission is not None:
                t = mat.pb_transmission if mat.pb_transmission is not None else 0.0
                f.write(f"Tf {t:.6f} {t:.6f} {t:.6f}\n")

            # Texture maps
            if mat.map_Kd:
                f.write(f"map_Kd {mat.map_Kd}\n")
            if mat.map_Ks:
                f.write(f"map_Ks {mat.map_Ks}\n")
            if mat.map_Ke:
                f.write(f"map_Ke {mat.map_Ke}\n")
            if mat.map_d:
                f.write(f"map_d {mat.map_d}\n")
            if mat.map_bump:
                f.write(f"bump {mat.map_bump}\n")

            # pb_* extensions
            if mat.pb_brdf:
                f.write(f"pb_brdf {mat.pb_brdf}\n")
            if mat.pb_semantic:
                f.write(f"pb_semantic {mat.pb_semantic}\n")
            if mat.pb_roughness is not None:
                f.write(f"pb_roughness {mat.pb_roughness:.6f}\n")
            if mat.pb_roughness_x is not None:
                f.write(f"pb_roughness_x {mat.pb_roughness_x:.6f}\n")
            if mat.pb_roughness_y is not None:
                f.write(f"pb_roughness_y {mat.pb_roughness_y:.6f}\n")
            if mat.pb_anisotropy is not None:
                f.write(f"pb_anisotropy {mat.pb_anisotropy:.6f}\n")
            if mat.pb_eta is not None:
                f.write(f"pb_eta {mat.pb_eta:.4f}\n")
            if mat.pb_conductor_eta:
                e = mat.pb_conductor_eta
                f.write(f"pb_conductor_eta {e[0]:.4f} {e[1]:.4f} {e[2]:.4f}\n")
            if mat.pb_conductor_k:
                k = mat.pb_conductor_k
                f.write(f"pb_conductor_k {k[0]:.4f} {k[1]:.4f} {k[2]:.4f}\n")
            if mat.pb_transmission is not None:
                f.write(f"pb_transmission {mat.pb_transmission:.4f}\n")
            if mat.pb_thin is not None:
                f.write(f"pb_thin {mat.pb_thin}\n")
            if mat.pb_thickness is not None:
                f.write(f"pb_thickness {mat.pb_thickness:.6f}\n")
            if mat.pb_clearcoat is not None:
                f.write(f"pb_clearcoat {mat.pb_clearcoat:.4f}\n")
            if mat.pb_clearcoat_roughness is not None:
                f.write(f"pb_clearcoat_roughness {mat.pb_clearcoat_roughness:.6f}\n")
            if mat.pb_base_brdf:
                f.write(f"pb_base_brdf {mat.pb_base_brdf}\n")
            if mat.pb_base_roughness is not None:
                f.write(f"pb_base_roughness {mat.pb_base_roughness:.6f}\n")
            if mat.pb_sheen is not None:
                f.write(f"pb_sheen {mat.pb_sheen:.4f}\n")
            if mat.pb_sheen_tint is not None:
                f.write(f"pb_sheen_tint {mat.pb_sheen_tint:.4f}\n")

            f.write("\n")

    print(f"  MTL: {len(materials)} material(s) → {mtl_path}")
